name: flutterskeleton
description: Flutter Skeleton
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_ui_auth: ^1.9.1
  firebase_ui_firestore: ^1.5.13
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_riverpod: ^2.4.3
  go_router: ^11.1.3
  google_fonts: ^6.1.0
  intl: any
  logger: ^2.0.2+1
  riverpod_annotation: ^2.2.0
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
