default_platform(:ios)

platform :ios do

  lane :development do
    build_app(
      scheme: "dev",
      configuration: "Debug-dev",
      clean: true,
      output_directory: "../build/fastlane/ios",
      xcargs: "OTHER_CFLAGS=""-Wno-deprecated-builtins""")
  end

  lane :release do
    disable_automatic_code_signing
    build_app(
      scheme: "prod",
      configuration: "Release-prod",
      clean: true,
      output_directory: "../build/fastlane/ios",
      xcargs: "OTHER_CFLAGS=""-Wno-deprecated-builtins""")
    enable_automatic_code_signing
    upload_to_testflight
  end
end
